application: dkc-app
version: 1
runtime: python27
api_version: 1
threadsafe: false
inbound_services:
- warmup

skip_files:
- ^(.*/)?.*\.pyc
- .DS_Store

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: dkc/static/favicon.ico
  upload: dkc/static/favicon\.ico
  expiration: 30d
- url: /(apple-touch-icon.*\.(png))
  static_files: dkc/static/\1
  upload: dkc/static/(apple-touch-icon.*\.png)
  expiration: 30d
- url: /images
  static_dir: dkc/static/images
  expiration: 14d
- url: /css
  static_dir: dkc/static/css
  expiration: 7d
- url: /js
  static_dir: dkc/static/js
  expiration: 7d
- url: /fonts
  static_dir: dkc/static/fonts
  expiration: 7d
- url: /admin
  script: dkc.manage.views.application
- url: /admin/stats.*
  script: google.appengine.ext.appstats.ui.app
- url: /admin.*
  script: dkc.manage.views.application
  login: admin
- url: /.*
  script: dkc.views.application

env_variables:
    TZ: 'EST'
